pipeline {
    agent {
        kubernetes {
            defaultContainer 'helm'
            yaml '''
spec:
  serviceAccountName: jenkins
  volumes: []

  containers:
    - name: helm
      image: ghcr.io/helmfile/helmfile-debian-stable-slim
      command:
        - sleep
      args:
        - 99d
'''
        }
    }

    environment {
        HELM_REGISTRY = 'https://nexus.berdyuhin.com/repository/helm/'
        HELM_REGISTRY_CREDS = credentials('nexus')
        WORK_DIR = "${WORKSPACE}/k8s/helm_charts/common"
    }

    stages {
        stage('Build') {
            steps {
                sh 'cd ${WORK_DIR} && helm package ./'
            }
        }

        stage('Push') {
            steps {
                script {
                    def chartyaml = readYaml file: "${WORK_DIR}/Chart.yaml"
                    def chartName = chartyaml.name
                    def chartVersion = chartyaml.version

                    sh("cd ${WORK_DIR} && curl -u ${HELM_REGISTRY_CREDS_USR}:${HELM_REGISTRY_CREDS_PSW} --upload-file ${chartName}-${chartVersion}.tgz ${HELM_REGISTRY}")
                }
            }
        }
    }
}