apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "cron-job.fullname" . }}
  labels:
    {{- include "cron-job.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.schedule | quote }}
  jobTemplate:
    spec:
      template:
        spec:
          {{- with .Values.imagePullSecrets }}
          imagePullSecrets:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          serviceAccountName: {{ include "cron-job.serviceAccountName" . }}
          securityContext:
            {{- toYaml .Values.podSecurityContext | nindent 12 }}
          containers:
            - name: {{ .Chart.Name }}
              image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
              env:
              {{- range $key, $val := .Values.env }}
                - name: {{ $key }}
                  valueFrom:
                    secretKeyRef:
                      name: {{ $.Release.Name }}-envs
                      key: {{ $key }}
              {{- end}}
          restartPolicy: OnFailure